# Generated by Django 4.2.2 on 2023-08-20 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0003_rename_comments_comment_rename_likes_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="repost",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="post",
            name="user_id",
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_liked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent_comment_id",
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
