# Generated by Django 4.2.2 on 2023-08-22 23:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0004_rename_user_id_comment_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent_comment_id",
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.AlterField(
            model_name="repost",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                related_name="users_liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
