# Generated by Django 4.2.2 on 2023-08-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(default="bio", max_length=300),
            preserve_default=False,
        ),
    ]
